### ISSUE TITLE
აცდენილი პასუხები

### ISSUE THREAD

**Issue by LevanSamadashvili** [freeuni-paradigms/07-where-am-i#1]
საბოლოო where-am-i ტესტის 3 რიცხვი არ ემთხვევა ტესტში რაც წერია იმას (ბოლო 1 ციფრია ხოლმე განსხვავება, ძალიან ცოტა ნუ). შეიძლება გასწორება რამენაირად თუ დავტოვოთ მასე

**Comment by mdzam18** [comment]
გამარჯობა, ვფიქრობ, შესაძლოა სადმე შეცდომა გაქვს. შეიძლება თვითონ ბოლო ფუნქცია სწორად გიწერია, მაგრამ მასში გამოყენებული რომელიმე ფუნქციაა არასწორად იმპლემენტირებული. შესაძლოა ეს პრობლემა average-point-ის არასწორ იმპლემენტაციას გამოეწვია.

**Comment by LevanSamadashvili** [comment]
ვნახავ, მადლობა
